# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LlmWiki < Formula
  desc "CLI + TUI for creating and managing LLM wikis"
  homepage "https://github.com/DavDaz/llm-wiki-generator"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DavDaz/llm-wiki-generator/releases/download/v0.3.1/llm-wiki_darwin_amd64.tar.gz"
      sha256 "95cea49500cf30df2a0216fa889ce7654083f1be3a2754f5da60a169250310e4"

      define_method(:install) do
        bin.install "llm-wiki"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DavDaz/llm-wiki-generator/releases/download/v0.3.1/llm-wiki_darwin_arm64.tar.gz"
      sha256 "18a9bad9dbecc3dfdbff3d5882c22170abb393621888b8f524ca393374efda00"

      define_method(:install) do
        bin.install "llm-wiki"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/DavDaz/llm-wiki-generator/releases/download/v0.3.1/llm-wiki_linux_amd64.tar.gz"
      sha256 "f91d2988103e2b9cd6a9e7aff04d3873d1b0898bbac2f87042bceb3b4d981ee0"
      define_method(:install) do
        bin.install "llm-wiki"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DavDaz/llm-wiki-generator/releases/download/v0.3.1/llm-wiki_linux_arm64.tar.gz"
      sha256 "a58864b77f7a09eba63e16712deb29d42c3e06ba85b417b6c1d0726848e110ec"
      define_method(:install) do
        bin.install "llm-wiki"
      end
    end
  end

  test do
    system "#{bin}/llm-wiki version"
  end
end
